using UnityEngine;

namespace CierzoArena.Environment
{
    /// <summary>
    /// Declares the gameplay policy of an environment collider generated by the
    /// arena builders.  It deliberately lives on a generated gameplay object rather
    /// than on an Occa Software prefab, keeping package assets presentation-only.
    /// </summary>
    public sealed class EnvironmentObstacle : MonoBehaviour
    {
        public enum Category
        {
            Ground,
            BridgeDeck,
            House,
            TownCenter,
            TreeObstacle,
            TreeCluster,
            CliffBoundary,
            Structure,
            Trigger,
        }

        [SerializeField] private Category category;
        [SerializeField] private Transform visualRoot;
        [SerializeField] private bool excludesFromNavMesh = true;

        public Category ObstacleCategory => category;
        public Transform VisualRoot => visualRoot;
        public bool ExcludesFromNavMesh => excludesFromNavMesh;

        public void Configure(Category value, Transform visual, bool blocksNavigation)
        {
            category = value;
            visualRoot = visual;
            excludesFromNavMesh = blocksNavigation;
        }

#if UNITY_EDITOR
        private void OnDrawGizmosSelected()
        {
            Collider collider = GetComponent<Collider>();
            if (collider == null) return;
            Gizmos.color = excludesFromNavMesh ? Color.red : Color.green;
            Gizmos.DrawWireCube(collider.bounds.center, collider.bounds.size);
            if (visualRoot != null)
            {
                Gizmos.color = Color.cyan;
                Gizmos.DrawLine(collider.bounds.center, visualRoot.position);
            }
        }
#endif
    }
}
