#if UNITY_EDITOR
using CierzoArena.Environment;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace CierzoArena.EditorTools
{
    /// <summary>Small, explicit M23 maintenance actions. They affect only roots
    /// generated by the environment builders and never alter package prefabs.</summary>
    public static class M23EnvironmentCommands
    {
        [MenuItem("Cierzo Arena/Environment/Rebuild M23 Environment")]
        public static void Rebuild()
        {
            FantasyVillageMaterialRemapper.RebuildVariants();
            MobaGreyboxArenaBuilder.CreateMobaGreyboxArena();
        }

        [MenuItem("Cierzo Arena/Environment/Clean Generated M23 Environment")]
        public static void Clean()
        {
            FantasyVillageMapAmbienceBuilder.CleanGenerated();
            GameObject bases = GameObject.Find("Bases");
            if (bases != null)
            {
                foreach (Transform baseRoot in bases.transform)
                {
                    foreach (string childName in new[] { "Gameplay", "Visuals", "Debug" })
                    {
                        Transform child = baseRoot.Find(childName);
                        if (child != null) Object.DestroyImmediate(child.gameObject);
                    }
                }
            }
            EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());
            Debug.Log("M23 cleanup removed only generated base and ambience roots. Gameplay structures, colliders and routes remain.");
        }
    }
}
#endif
