using System;
using System.Collections.Generic;
using UnityEngine;

namespace CierzoArena.Units
{
    /// <summary>Stable central roster shared by menu, local play and server spawn.
    /// The development fallback is data-driven so the prototype is playable before
    /// final authored assets replace it.</summary>
    [CreateAssetMenu(fileName = "HeroCatalog", menuName = "Cierzo Arena/Hero Catalog")]
    public sealed class HeroCatalog : ScriptableObject
    {
        [SerializeField] private HeroDefinition[] heroes = Array.Empty<HeroDefinition>();
        private readonly Dictionary<string, HeroDefinition> byId = new(StringComparer.Ordinal);
        private bool indexed;
        private static HeroCatalog shared;

        public static HeroCatalog Shared
        {
            get
            {
                if (shared != null) return shared;
                shared = Resources.Load<HeroCatalog>("Heroes/HeroCatalog");
                if (shared == null) shared = HeroRosterFactory.CreateDevelopmentCatalog();
                shared.Reindex(); return shared;
            }
        }

        public IReadOnlyList<HeroDefinition> Heroes { get { Reindex(); return heroes; } }
        public HeroDefinition DefaultHero { get { Reindex(); return heroes != null && heroes.Length > 0 ? heroes[0] : null; } }

        public bool TryGet(string heroId, out HeroDefinition definition)
        {
            definition=null;Reindex();
            return !string.IsNullOrWhiteSpace(heroId) && byId.TryGetValue(heroId, out definition) && definition != null;
        }
        public HeroDefinition ResolveOrFallback(string heroId)
        {
            if (TryGet(heroId, out HeroDefinition definition)) return definition;
            return DefaultHero;
        }
        public void BindDevelopmentPrefab(GameObject prefab)
        {
            if (prefab == null) return;
            Reindex();
            for (int i=0;i<heroes.Length;i++) if (heroes[i] != null && heroes[i].Prefab == null) heroes[i].SetPrefab(prefab);
        }
        public bool Validate(out string reason)
        {
            reason=string.Empty;Reindex();
            if (heroes == null || heroes.Length < 20) { reason="The roster must contain at least twenty heroes."; return false; }
            HashSet<string> ids=new(StringComparer.Ordinal);
            for(int i=0;i<heroes.Length;i++)
            {
                if(heroes[i]==null){reason="Catalog contains a null hero definition.";return false;}
                if(!heroes[i].IsValid(false,out reason)) return false;
                if(!ids.Add(heroes[i].HeroId)){reason=$"Duplicate HeroId: {heroes[i].HeroId}.";return false;}
            }
            reason=string.Empty;return true;
        }
        public void SetDefinitionsForTests(HeroDefinition[] definitions) { heroes=definitions ?? Array.Empty<HeroDefinition>(); indexed=false; Reindex(); }
        private void Reindex()
        {
            if(indexed)return;byId.Clear();
            if(heroes!=null) for(int i=0;i<heroes.Length;i++)
            {
                HeroDefinition hero=heroes[i];
                if(hero==null||string.IsNullOrWhiteSpace(hero.HeroId)||byId.ContainsKey(hero.HeroId)) continue;
                byId.Add(hero.HeroId,hero);
            }
            indexed=true;
        }
    }

    internal static class HeroRosterFactory
    {
        public static HeroCatalog CreateDevelopmentCatalog()
        {
            HeroCatalog catalog=ScriptableObject.CreateInstance<HeroCatalog>();
            HeroDefinition[] roster =
            {
                Create("stone_aegis","Stone Aegis","Bastion of the windbreak","A resilient initiator who holds ground and scatters attackers.",HeroRole.Vanguard,HeroRole.Controller,HeroAttackStyle.Melee,1,new Color(.32f,.66f,.72f),new HeroStats(680,105,220,18,3,4,42,5,4.7f,.12f,2.5f,1.35f,.24f,.36f,12f), new[]{Kit("rampart_strike","Rampart Strike",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,35,7,55,5,2.1f,0),Kit("windward_guard","Windward Guard",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,40,12,120,0,0,4),Kit("grounding_ring","Grounding Ring",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,45,11,.42f,5,2.8f,2.5f),Kit("citadel_crash","Citadel Crash",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,90,70,130,6,3.4f,1.8f)}),
                Create("rift_duelist","Rift Duelist","Blade at the gale's edge","A close-range skirmisher who converts tempo into pressure.",HeroRole.Duelist,HeroRole.Carry,HeroAttackStyle.Melee,2,new Color(.86f,.34f,.22f),new HeroStats(540,82,240,20,2,5,57,8,5.9f,.2f,2.35f,1.05f,.18f,.28f,13f), new[]{Kit("rift_lunge","Rift Lunge",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,35,6,62,5,1.4f,0),Kit("duelist_wind","Duelist Wind",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,12,1.4f,0,0,4),Kit("counterveil","Counterveil",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,45,14,100,0,0,3),Kit("redline","Redline",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,90,65,155,5,2.4f,0)}),
                Create("skyline_marksman","Skyline Marksman","Arrow of the open current","A ranged carry with precise projectile pressure.",HeroRole.Carry,HeroRole.Controller,HeroAttackStyle.Ranged,2,new Color(.94f,.78f,.25f),new HeroStats(470,65,260,22,1.6f,6,54,9,5.35f,.16f,8.5f,1.12f,.22f,.3f,20f), new[]{Kit("piercing_gale","Piercing Gale",AbilityTargeting.UnitTarget,AbilityEffect.ProjectileDamage,40,7,70,10,0,0),Kit("tailwind","Tailwind",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,13,1.1f,0,0,4),Kit("updraft_step","Updraft Step",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,45,15,1.8f,0,0,1.5f),Kit("horizon_breaker","Horizon Breaker",AbilityTargeting.UnitTarget,AbilityEffect.ProjectileDamage,95,70,175,14,0,0)}),
                Create("storm_warden","Storm Warden","Keeper of the high current","A battlefield mage who punishes clustered foes with charged weather.",HeroRole.Mage,HeroRole.Controller,HeroAttackStyle.Ranged,2,new Color(.20f,.62f,1f),new HeroStats(455,60,330,32,1.4f,7.5f,38,6,5.1f,.12f,7.5f,1.3f,.25f,.32f,18f), new[]{Kit("arc_bolt","Arc Bolt",AbilityTargeting.UnitTarget,AbilityEffect.ProjectileDamage,35,6,68,10,0,0),Kit("storm_mark","Storm Mark",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,45,10,72,8,2.7f,0),Kit("gale_step","Gale Step",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,30,14,1.5f,0,0,3),Kit("tempest_fall","Tempest Fall",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,90,70,145,10,3.5f,1.4f)}),
                Create("cairn_warden","Cairn Warden","Shelter for the stormbound","A protective support who trades damage for durable protection.",HeroRole.Support,HeroRole.Vanguard,HeroAttackStyle.Ranged,1,new Color(.48f,.88f,.58f),new HeroStats(560,88,310,30,2.7f,7,35,4,5.0f,.13f,6.5f,1.38f,.28f,.35f,16f), new[]{Kit("kindling_orb","Kindling Orb",AbilityTargeting.UnitTarget,AbilityEffect.ProjectileDamage,30,6,42,8,0,0),Kit("cairn_barrier","Cairn Barrier",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,45,11,145,0,0,5),Kit("restoring_draft","Restoring Draft",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,13,.9f,0,0,5),Kit("sanctuary_field","Sanctuary Field",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,85,70,.35f,8,4,4)}),
                Create("tempest_arbiter","Tempest Arbiter","Voice between thunderheads","A zone controller whose storms deny routes and isolate targets.",HeroRole.Controller,HeroRole.Mage,HeroAttackStyle.Ranged,3,new Color(.70f,.38f,.94f),new HeroStats(490,70,300,34,1.8f,7.2f,43,6,5.25f,.14f,7.2f,1.27f,.25f,.33f,17f), new[]{Kit("pressure_drop","Pressure Drop",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,35,7,.48f,8,2.5f,2.5f),Kit("static_lattice","Static Lattice",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,50,13,50,8,2.5f,1),Kit("crosswind","Crosswind",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,14,1.2f,0,0,4),Kit("eye_of_tempest","Eye of Tempest",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,95,72,165,10,4.2f,0)})
                ,N("ember_bastion","Ember Bastion","Shield of the living kiln","A fire-forged vanguard who turns enemy pressure into a burning frontline.",HeroRole.Vanguard,HeroRole.Controller,HeroAttackStyle.Melee,1,new Color(.92f,.28f,.12f),new HeroStats(710,110,230,19,3.4f,4.2f,45,5,4.65f,.11f,2.45f,1.38f,.26f,.38f,12f),HeroDamageType.Magical,HeroPowerCurve.Early,new[]{"Tank","Initiation","Peel","Low mobility"},new[]{A("ember_bastion.cinder_ram","Cinder Ram","Charge to a point and scorch foes in the impact area.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,40,8,58,5,2.2f,0),A("ember_bastion.kiln_plate","Kiln Plate","Raise a heat shield that absorbs damage before cracking.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,45,13,125,0,0,4),A("ember_bastion.ash_ring","Ash Ring","A ring of ash slows enemies trying to leave its centre.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,50,12,.32f,6,3f,3),A("ember_bastion.furnace_gate","Furnace Gate","Erupt a wide furnace gate that stuns and burns clustered enemies.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,95,76,145,7,3.8f,1.5f,3)})
                ,N("ironroot_colossus","Ironroot Colossus","The walking watershed","A stone-and-root guardian that anchors allies with durable terrain control.",HeroRole.Vanguard,HeroRole.Support,HeroAttackStyle.Melee,2,new Color(.27f,.58f,.31f),new HeroStats(735,112,205,16,3.7f,3.6f,43,5,4.45f,.1f,2.5f,1.42f,.28f,.4f,11f),HeroDamageType.Physical,HeroPowerCurve.Mid,new[]{"Tank","Sustain","Zone control","Low mobility"},new[]{A("ironroot_colossus.root_hook","Root Hook","Tear a root line through foes and damage the landing area.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,40,9,54,5.5f,2f,0),A("ironroot_colossus.barkward","Barkward","Wrap the Colossus in layered bark shielding.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,42,12,140,0,0,5),A("ironroot_colossus.moss_quake","Moss Quake","Mossy ground slows enemies who cross the tremor.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,50,11,.38f,6,3.1f,3),A("ironroot_colossus.worldroot","Worldroot","Raise an ancient root pulse that stuns a broad area.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,90,78,125,7.5f,4.1f,1.7f,3)})
                ,N("frostveil_sentinel","Frostveil Sentinel","Watcher of the blue pass","A deliberate ice sentinel who controls entries and protects retreats.",HeroRole.Vanguard,HeroRole.Controller,HeroAttackStyle.Melee,2,new Color(.38f,.76f,.96f),new HeroStats(670,100,270,24,3,5.7f,41,5,4.8f,.1f,2.55f,1.4f,.27f,.37f,12f),HeroDamageType.Magical,HeroPowerCurve.Mid,new[]{"Tank","Crowd control","Peel","Low mobility"},new[]{A("frostveil_sentinel.ice_lance","Ice Lance","Hurl a cold lance that bursts at the targeted point.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,42,8,60,6,2f,0),A("frostveil_sentinel.rime_guard","Rime Guard","Coat yourself in rime for a strong temporary shield.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,45,13,130,0,0,4),A("frostveil_sentinel.hoarfrost_field","Hoarfrost Field","Freeze the ground to slow advancing enemies.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,48,11,.42f,7,3.2f,3),A("frostveil_sentinel.whiteout","Whiteout","Call a whiteout that stuns foes caught in its eye.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,95,74,135,8,4f,1.6f,3)})
                ,N("ashen_vow","Ashen Vow","Oathblade of the last spark","A hybrid oath knight who wins prolonged duels through disciplined risk.",HeroRole.Duelist,HeroRole.Vanguard,HeroAttackStyle.Melee,2,new Color(.64f,.18f,.14f),new HeroStats(610,92,250,20,2.6f,4.8f,55,7,5.45f,.18f,2.3f,1.12f,.2f,.3f,13f),HeroDamageType.Hybrid,HeroPowerCurve.Mid,new[]{"Duelist","Sustain","Split push","Medium mobility"},new[]{A("ashen_vow.oath_cleave","Oath Cleave","Sweep a vowblade through enemies at the chosen point.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,36,7,66,4.5f,1.9f,0),A("ashen_vow.cinder_oath","Cinder Oath","Bind yourself in a protective cinder vow.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,42,13,105,0,0,4),A("ashen_vow.penitent_stride","Penitent Stride","Gain a brief burst of movement to re-engage or escape.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,12,1.45f,0,0,3),A("ashen_vow.last_vow","Last Vow","Drive a searing oath into an area for heavy finishing damage.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,90,70,165,5,2.6f,0,3)})
                ,N("zephyr_reaver","Zephyr Reaver","Blade of the unmoored sky","A mobile assassin who cuts openings before the wind carries him away.",HeroRole.Assassin,HeroRole.Duelist,HeroAttackStyle.Melee,3,new Color(.18f,.83f,.75f),new HeroStats(500,70,260,22,1.8f,5.5f,61,9,6.05f,.22f,2.2f,1.0f,.16f,.25f,14f),HeroDamageType.Physical,HeroPowerCurve.Early,new[]{"Assassin","High mobility","Burst","Risky"},new[]{A("zephyr_reaver.gust_cut","Gust Cut","Dash-cut to a point and damage foes around the landing mark.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,38,7,68,5.5f,1.5f,0),A("zephyr_reaver.windskin","Windskin","Wrap in a light shield before committing to a pick.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,38,14,85,0,0,2.5f),A("zephyr_reaver.slipstream","Slipstream","Surge through a slipstream for exceptional move speed.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,11,1.85f,0,0,2.5f),A("zephyr_reaver.sky_sunder","Sky Sunder","Carve a lethal pressure break into a small target area.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,90,68,180,6,2.2f,0,3)})
                ,N("thornbound","Thornbound","The briar that will not break","A relentless bruiser who trades reach for sticking power and lane pressure.",HeroRole.Duelist,HeroRole.Carry,HeroAttackStyle.Melee,2,new Color(.31f,.72f,.23f),new HeroStats(625,95,215,17,3.2f,3.8f,58,8,5.45f,.17f,2.35f,1.08f,.19f,.29f,13f),HeroDamageType.Physical,HeroPowerCurve.Mid,new[]{"Bruiser","Sustain","Split push","Medium mobility"},new[]{A("thornbound.briar_snap","Briar Snap","Snap thorny vines at a point for close area damage.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,36,7,64,4.7f,1.8f,0),A("thornbound.ironbark","Ironbark","Harden bark into a duelist shield.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,40,13,115,0,0,4),A("thornbound.creeping_vines","Creeping Vines","Vines slow enemies while Thornbound closes the distance.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,45,11,.36f,5.5f,2.8f,3),A("thornbound.wild_bloom","Wild Bloom","Detonate a wild bloom for a powerful area strike.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,88,70,170,5,3f,0,3)})
                ,N("cinderlash","Cinderlash","The wildfire's answer","A whip-wielding skirmisher who bursts forward but folds under return fire.",HeroRole.Duelist,HeroRole.Carry,HeroAttackStyle.Melee,3,new Color(.98f,.46f,.12f),new HeroStats(525,76,245,21,2.1f,5.2f,63,9,5.8f,.2f,2.25f,1.02f,.17f,.27f,14f),HeroDamageType.Physical,HeroPowerCurve.Early,new[]{"Skirmisher","Burst","High mobility","Fragile"},new[]{A("cinderlash.flare_lash","Flare Lash","Crack a flaming lash at a point for explosive area damage.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,38,6,70,5.5f,1.7f,0),A("cinderlash.coal_guard","Coal Guard","Bank a thin coal shield before diving.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,38,14,90,0,0,3),A("cinderlash.sparkskip","Sparkskip","Ride a spray of sparks for a rapid movement burst.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,34,10,1.75f,0,0,2.5f),A("cinderlash.pyreline","Pyreline","Ignite a volatile line with a devastating small-area blast.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,92,69,185,6.5f,2.4f,0,3)})
                ,N("sunspoke_ranger","Sunspoke Ranger","Arrow through first light","A patient physical carry who rewards positioning and clear sightlines.",HeroRole.Carry,HeroRole.Controller,HeroAttackStyle.Ranged,2,new Color(1f,.77f,.18f),new HeroStats(465,62,280,24,1.5f,6.1f,56,10,5.25f,.15f,8.8f,1.08f,.2f,.28f,21f),HeroDamageType.Physical,HeroPowerCurve.Late,new[]{"Ranged carry","Poke","Late game","Low mobility"},new[]{A("sunspoke_ranger.sunpin","Sunpin","Fire a bright bolt that damages the target area from range.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,40,7,72,10,1.6f,0),A("sunspoke_ranger.glare_ward","Glare Ward","A light guard protects the Ranger from a counter-engage.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,42,15,80,0,0,3),A("sunspoke_ranger.golden_draft","Golden Draft","Take a short golden wind to reposition.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,35,14,1.15f,0,0,3),A("sunspoke_ranger.dawnspear","Dawnspear","Launch a brilliant long-range spear for huge area damage.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,95,73,190,12,2.7f,0,3)})
                ,N("glaciershard","Glaciershard","The crystal winter","An artillery mage whose fragments punish enemies that stand together.",HeroRole.Mage,HeroRole.Controller,HeroAttackStyle.Ranged,2,new Color(.45f,.84f,1f),new HeroStats(440,58,345,34,1.3f,7.8f,37,6,5.05f,.11f,7.8f,1.32f,.25f,.32f,18f),HeroDamageType.Magical,HeroPowerCurve.Late,new[]{"Mage","Artillery","Zone control","Low mobility"},new[]{A("glaciershard.shatterbolt","Shatterbolt","Detonate a shard at range to damage a compact area.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,42,7,78,9,2.3f,0),A("glaciershard.crystal_sheen","Crystal Sheen","Cover yourself in a fragile ice shield.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,45,15,75,0,0,3),A("glaciershard.permafrost","Permafrost","Lay permafrost to slow enemies entering the zone.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,50,10,.4f,8,3.2f,3.5f),A("glaciershard.avalanche_prism","Avalanche Prism","Collapse a massive prism for high area damage.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,100,75,195,10,4f,0,3)})
                ,N("verdant_cantor","Verdant Cantor","Voice of the green current","A utility support whose living songs create safe paths and sustained pressure.",HeroRole.Support,HeroRole.Utility,HeroAttackStyle.Ranged,2,new Color(.25f,.86f,.44f),new HeroStats(505,76,325,31,2.4f,7.4f,36,5,5.15f,.13f,6.8f,1.34f,.26f,.34f,16f),HeroDamageType.Magical,HeroPowerCurve.Mid,new[]{"Support","Utility","Sustain","Peel"},new[]{A("verdant_cantor.seedburst","Seedburst","Send a seedburst that damages enemies in its bloom.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,38,7,52,7.5f,2.1f,0),A("verdant_cantor.chorus_bark","Chorus Bark","Sing a protective bark shield around yourself.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,42,11,130,0,0,5),A("verdant_cantor.trailing_song","Trailing Song","Accelerate on a trailing song to rotate between allies.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,34,12,1.05f,0,0,4),A("verdant_cantor.grove_refrain","Grove Refrain","Plant a resonant grove that strongly slows enemies in its space.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,88,72,.5f,8,4.1f,5,3)})
                ,N("umbral_sable","Umbral Sable","The dusk between sparks","A shadow hybrid assassin with lethal flanks and little room for mistakes.",HeroRole.Assassin,HeroRole.Duelist,HeroAttackStyle.Melee,3,new Color(.36f,.2f,.58f),new HeroStats(480,67,285,25,1.7f,6.4f,59,9,5.95f,.22f,2.15f,1.0f,.15f,.24f,14f),HeroDamageType.Hybrid,HeroPowerCurve.Early,new[]{"Assassin","Burst","High mobility","High difficulty"},new[]{A("umbral_sable.night_pierce","Night Pierce","Blink through a point with a burst of shadow damage.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,40,7,74,5.8f,1.5f,0),A("umbral_sable.eclipsed_skin","Eclipsed Skin","Shroud yourself in a short-lived umbral shield.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,40,14,88,0,0,2.5f),A("umbral_sable.duskstep","Duskstep","Move at extreme speed while slipping around vision lines.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,36,11,1.9f,0,0,2.3f),A("umbral_sable.black_sun","Black Sun","Collapse darkness over a kill zone for massive burst damage.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaDamage,95,70,195,6,2.5f,0,3)})
                ,N("lumenweaver","Lumenweaver","Stitcher of the dawnline","A defensive light support who excels at saving allies rather than finishing foes.",HeroRole.Support,HeroRole.Utility,HeroAttackStyle.Ranged,1,new Color(1f,.92f,.55f),new HeroStats(520,80,350,33,2.5f,8f,33,4,5.05f,.12f,6.7f,1.36f,.27f,.35f,16f),HeroDamageType.Magical,HeroPowerCurve.Mid,new[]{"Support","Defensive","Peel","Low damage"},new[]{A("lumenweaver.lumen_orb","Lumen Orb","Send an orb of light that bursts for modest area damage.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,35,7,48,7.5f,2f,0),A("lumenweaver.prism_shroud","Prism Shroud","Weave a strong luminous shield for a threatened position.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,48,11,155,0,0,5),A("lumenweaver.guiding_ray","Guiding Ray","Take a guiding ray to reposition behind allies.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,32,13,.95f,0,0,4),A("lumenweaver.daybreak_circle","Daybreak Circle","Create a wide dawn circle that heavily slows hostile divers.",AbilityTargeting.PointTarget,AbilityEffect.AreaSlow,90,74,.48f,8,4.3f,5,3)})
                ,N("prism_oracle","Prism Oracle","Reader of a thousand refractions","A precise arcane controller who wins fights by making routes unsafe.",HeroRole.Controller,HeroRole.Mage,HeroAttackStyle.Ranged,3,new Color(.82f,.48f,1f),new HeroStats(470,64,355,35,1.5f,8.2f,40,6,5.15f,.13f,7.4f,1.3f,.24f,.32f,18f),HeroDamageType.Magical,HeroPowerCurve.Late,new[]{"Controller","Poke","Zone control","High difficulty"},new[]{A("prism_oracle.refraction","Refraction","Fire a refracted burst into a chosen area.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,42,7,70,8.5f,2.2f,0),A("prism_oracle.mirror_shell","Mirror Shell","Surround yourself with a reflective arcane shield.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,45,14,100,0,0,4),A("prism_oracle.angle_shift","Angle Shift","Shift along a refracted angle with extra movement speed.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,34,13,1.25f,0,0,3.5f),A("prism_oracle.zenith_array","Zenith Array","Trigger a precise prism array that stuns enemies in a wide field.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,98,76,140,9,4.2f,1.4f,3)})
                ,N("tidebinder","Tidebinder","Keeper of the returning shore","A water controller who creates powerful rotations and protects the backline.",HeroRole.Controller,HeroRole.Support,HeroAttackStyle.Ranged,2,new Color(.16f,.55f,.9f),new HeroStats(535,82,320,30,2.5f,7.3f,39,5,5.2f,.14f,7f,1.31f,.25f,.33f,17f),HeroDamageType.Magical,HeroPowerCurve.Mid,new[]{"Controller","Support","Zone control","Peel"},new[]{A("tidebinder.surge_orb","Surge Orb","Release a tide orb that breaks over a target area.",AbilityTargeting.PointTarget,AbilityEffect.AreaDamage,38,7,58,8,2.2f,0),A("tidebinder.foamward","Foamward","Wrap yourself in a resilient foam shield.",AbilityTargeting.NoTarget,AbilityEffect.SelfShield,43,12,135,0,0,4.5f),A("tidebinder.currentwalk","Currentwalk","Ride a returning current for rapid movement.",AbilityTargeting.NoTarget,AbilityEffect.SelfMoveSpeed,34,12,1.2f,0,0,4),A("tidebinder.maelstrom_basin","Maelstrom Basin","Summon a basin whose violent current stuns and damages enemies.",AbilityTargeting.PointTarget,AbilityEffect.StrongAreaStun,94,74,150,8.5f,4.3f,1.5f,3)})
            };
            catalog.SetDefinitionsForTests(roster);return catalog;
        }
        private static HeroDefinition Create(string id,string name,string title,string description,HeroRole primary,HeroRole secondary,HeroAttackStyle style,int difficulty,Color color,HeroStats stats,AbilityDefinition[] kit)
        { HeroDefinition definition=ScriptableObject.CreateInstance<HeroDefinition>();definition.ConfigureRuntime(id,name,title,description,primary,secondary,style,difficulty,color,stats,kit);Texture2D portrait=Resources.Load<Texture2D>($"Art/UI/HeroPortraits/{PortraitFileName(id)}") ?? CreatePortrait(color,primary);definition.SetPresentation(portrait,portrait);return definition; }
        private static HeroDefinition N(string id,string name,string title,string description,HeroRole primary,HeroRole secondary,HeroAttackStyle style,int difficulty,Color color,HeroStats stats,HeroDamageType damage,HeroPowerCurve curve,string[] tags,AbilityDefinition[] kit)
        { HeroDefinition definition=Create(id,name,title,description,primary,secondary,style,difficulty,color,stats,kit);definition.ConfigureRuntime(id,name,title,description,primary,secondary,style,difficulty,color,stats,kit,damage,curve,tags);return definition; }
        private static AbilityDefinition Kit(string id,string name,AbilityTargeting target,AbilityEffect effect,float mana,float cooldown,float value,float range,float radius,float duration)
        { return A(id,name,name+" — a signature ability from the founding roster.",target,effect,mana,cooldown,value,range,radius,duration); }
        private static AbilityDefinition A(string id,string name,string description,AbilityTargeting target,AbilityEffect effect,float mana,float cooldown,float value,float range,float radius,float duration,int levels=4)
        { AbilityDefinition definition=ScriptableObject.CreateInstance<AbilityDefinition>();Texture2D icon=Resources.Load<Texture2D>($"Art/UI/AbilityIcons/{IconFileName(id)}") ?? CreateIcon(id);definition.ConfigureRuntime(id,name,description,target,effect,mana,cooldown,value,range,radius,duration,.2f,14f,icon,levels);return definition; }
        private static Texture2D CreatePortrait(Color color,HeroRole role)
        {
            const int size=256;Texture2D texture=new Texture2D(size,size,TextureFormat.RGBA32,false){name=role+" Portrait"};Color dark=Color.Lerp(color,Color.black,.72f);
            for(int y=0;y<size;y++)for(int x=0;x<size;x++){float dx=(x-size*.5f)/(size*.5f),dy=(y-size*.5f)/(size*.5f);float radius=Mathf.Sqrt(dx*dx+dy*dy);texture.SetPixel(x,y,Color.Lerp(color,dark,Mathf.Clamp01(radius))+(Mathf.Abs(dx)<.16f&&dy<.35f?Color.white*.12f:Color.black));}texture.Apply(false,true);return texture;
        }
        private static Texture2D CreateIcon(string id)
        {
            const int size=96;Texture2D texture=new Texture2D(size,size,TextureFormat.RGBA32,false){name=id+" Icon"};int hash=id.GetHashCode();Color baseColor=Color.HSVToRGB(Mathf.Abs(hash%360)/360f,.7f,.95f);Color dark=Color.Lerp(baseColor,Color.black,.78f);
            for(int y=0;y<size;y++)for(int x=0;x<size;x++){float dx=(x-size*.5f)/(size*.5f),dy=(y-size*.5f)/(size*.5f);float r=Mathf.Sqrt(dx*dx+dy*dy);float ray=Mathf.Abs(Mathf.Sin(Mathf.Atan2(dy,dx)*3f+(hash%7)));texture.SetPixel(x,y,r>.95f?Color.black:Color.Lerp(dark,baseColor,Mathf.Clamp01(1f-r+.22f*ray)));}texture.Apply(false,true);return texture;
        }
        private static string PortraitFileName(string id)
        {
            return id switch
            {
                "stone_aegis" => "StoneAegisPortrait",
                "rift_duelist" => "RiftDuelistPortrait",
                "skyline_marksman" => "SkylineMarksmanPortrait",
                "storm_warden" => "StormWardenPortrait",
                "cairn_warden" => "CairnWardenPortrait",
                "tempest_arbiter" => "TempestArbiterPortrait",
                _ => Pascal(id)+"Portrait"
            };
        }
        private static string IconFileName(string id) => Pascal(id)+"Icon";
        private static string Pascal(string id) { string[] words=id.Split(new[]{'.','_'},StringSplitOptions.RemoveEmptyEntries); string result=string.Empty; for(int i=0;i<words.Length;i++) result+=char.ToUpperInvariant(words[i][0])+words[i].Substring(1); return result; }
    }
}
